In [33]:
import numpy as np

In [13]:
iris = np.genfromtxt("../iris.csv", delimiter=";", skip_header=True, encoding="latin-1")
print(iris)
print(iris.dtype)
type(iris)

[[5.1 3.5 1.4 0.2 1. ]
 [4.9 3.  1.4 0.2 1. ]
 [4.7 3.2 1.3 0.2 1. ]
 [4.6 3.1 1.5 0.2 1. ]
 [5.  3.6 1.4 0.2 1. ]
 [5.4 3.9 1.7 0.4 1. ]
 [4.6 3.4 1.4 0.3 1. ]
 [5.  3.4 1.5 0.2 1. ]
 [4.4 2.9 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [5.4 3.7 1.5 0.2 1. ]
 [4.8 3.4 1.6 0.2 1. ]
 [4.8 3.  1.4 0.1 1. ]
 [4.3 3.  1.1 0.1 1. ]
 [5.8 4.  1.2 0.2 1. ]
 [5.7 4.4 1.5 0.4 1. ]
 [5.4 3.9 1.3 0.4 1. ]
 [5.1 3.5 1.4 0.3 1. ]
 [5.7 3.8 1.7 0.3 1. ]
 [5.1 3.8 1.5 0.3 1. ]
 [5.4 3.4 1.7 0.2 1. ]
 [5.1 3.7 1.5 0.4 1. ]
 [4.6 3.6 1.  0.2 1. ]
 [5.1 3.3 1.7 0.5 1. ]
 [4.8 3.4 1.9 0.2 1. ]
 [5.  3.  1.6 0.2 1. ]
 [5.  3.4 1.6 0.4 1. ]
 [5.2 3.5 1.5 0.2 1. ]
 [5.2 3.4 1.4 0.2 1. ]
 [4.7 3.2 1.6 0.2 1. ]
 [4.8 3.1 1.6 0.2 1. ]
 [5.4 3.4 1.5 0.4 1. ]
 [5.2 4.1 1.5 0.1 1. ]
 [5.5 4.2 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.2 1. ]
 [5.  3.2 1.2 0.2 1. ]
 [5.5 3.5 1.3 0.2 1. ]
 [4.9 3.6 1.4 0.1 1. ]
 [4.4 3.  1.3 0.2 1. ]
 [5.1 3.4 1.5 0.2 1. ]
 [5.  3.5 1.3 0.3 1. ]
 [4.5 2.3 1.3 0.3 1. ]
 [4.4 3.2 1.3 0.2 1. ]
 [5.  3.5 1

numpy.ndarray

In [14]:
np.savetxt("../iris_2.csv", iris, delimiter=";")

In [19]:
iris[2,1]

4.0

In [20]:
iris[2,1]=3.2
iris[2,1]

3.2

In [23]:
iris[iris > 2]

array([5.1, 3.5, 4.9, 3. , 4.7, 3.2, 4.6, 3.1, 5. , 3.6, 5.4, 3.9, 4.6,
       3.4, 5. , 3.4, 4.4, 2.9, 4.9, 3.1, 5.4, 3.7, 4.8, 3.4, 4.8, 3. ,
       4.3, 3. , 5.8, 4. , 5.7, 4.4, 5.4, 3.9, 5.1, 3.5, 5.7, 3.8, 5.1,
       3.8, 5.4, 3.4, 5.1, 3.7, 4.6, 3.6, 5.1, 3.3, 4.8, 3.4, 5. , 3. ,
       5. , 3.4, 5.2, 3.5, 5.2, 3.4, 4.7, 3.2, 4.8, 3.1, 5.4, 3.4, 5.2,
       4.1, 5.5, 4.2, 4.9, 3.1, 5. , 3.2, 5.5, 3.5, 4.9, 3.6, 4.4, 3. ,
       5.1, 3.4, 5. , 3.5, 4.5, 2.3, 4.4, 3.2, 5. , 3.5, 5.1, 3.8, 4.8,
       3. , 5.1, 3.8, 4.6, 3.2, 5.3, 3.7, 5. , 3.3, 7. , 3.2, 4.7, 6.4,
       3.2, 4.5, 6.9, 3.1, 4.9, 5.5, 2.3, 4. , 6.5, 2.8, 4.6, 5.7, 2.8,
       4.5, 6.3, 3.3, 4.7, 4.9, 2.4, 3.3, 6.6, 2.9, 4.6, 5.2, 2.7, 3.9,
       5. , 3.5, 5.9, 3. , 4.2, 6. , 2.2, 4. , 6.1, 2.9, 4.7, 5.6, 2.9,
       3.6, 6.7, 3.1, 4.4, 5.6, 3. , 4.5, 5.8, 2.7, 4.1, 6.2, 2.2, 4.5,
       5.6, 2.5, 3.9, 5.9, 3.2, 4.8, 6.1, 2.8, 4. , 6.3, 2.5, 4.9, 6.1,
       2.8, 4.7, 6.4, 2.9, 4.3, 6.6, 3. , 4.4, 6.8, 2.8, 4.8, 6.

In [25]:
iris[iris > 2].shape[0]

472

In [32]:
iris[iris[:,2] > 6]

array([[7.6, 3. , 6.6, 2.1, 3. ],
       [7.3, 2.9, 6.3, 1.8, 3. ],
       [7.2, 3.6, 6.1, 2.5, 3. ],
       [7.7, 3.8, 6.7, 2.2, 3. ],
       [7.7, 2.6, 6.9, 2.3, 3. ],
       [7.7, 2.8, 6.7, 2. , 3. ],
       [7.4, 2.8, 6.1, 1.9, 3. ],
       [7.9, 3.8, 6.4, 2. , 3. ],
       [7.7, 3. , 6.1, 2.3, 3. ]])

In [41]:
tableau = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print("contenu dans le tableau :")
print(tableau)
print("nouveau tableau auprès fancy indexing :")
tableau2 = np.array([[4,10,5],[12,9,9]])
tableau[tableau2]

contenu dans le tableau :
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
nouveau tableau auprès fancy indexing :


array([[ 5, 11,  6],
       [13, 10, 10]])

In [44]:
tableau[7:12]

array([ 8,  9, 10, 11, 12])

In [45]:
tableau[::8]

array([ 1,  9, 17])

In [46]:
iris[:5,:3]

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4]])

In [50]:
iris[145:,3:]

array([[2.3, 3. ],
       [1.9, 3. ],
       [2. , 3. ],
       [2.3, 3. ],
       [1.8, 3. ]])

In [52]:
iris[:,0]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [58]:
tableau = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
sous_tableau = tableau[:5].copy()
sous_tableau[0]=10
print(sous_tableau)
print(tableau)


[10  2  3  4  5]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [65]:
tableau3 = np.array([[15,21,3],[6,9,12],[24,27,30]])
tableau3

array([[15, 21,  3],
       [ 6,  9, 12],
       [24, 27, 30]])

In [69]:
np.add(tableau3,10)

array([[25, 31, 13],
       [16, 19, 22],
       [34, 37, 40]])

In [70]:
np.multiply(tableau3,20)

array([[300, 420,  60],
       [120, 180, 240],
       [480, 540, 600]])

In [72]:
np.sum(iris)

2378.7

In [76]:
#calcul par colonne
np.sum(iris,axis=0)

array([876.5, 458.6, 563.7, 179.9, 300. ])

In [77]:
#calcul par ligne
np.sum(iris,axis=1)

array([11.2, 10.5, 10.4, 10.4, 11.2, 12.4, 10.7, 11.1,  9.9, 10.6, 11.8,
       11. , 10.3,  9.5, 12.2, 13. , 12. , 11.3, 12.5, 11.7, 11.7, 11.7,
       10.4, 11.6, 11.3, 10.8, 11.4, 11.4, 11.2, 10.7, 10.7, 11.7, 11.9,
       12.3, 10.7, 10.6, 11.5, 11. ,  9.9, 11.2, 11.1,  9.4, 10.1, 11.7,
       12.2, 10.5, 11.7, 10.4, 11.7, 10.9, 18.3, 17.6, 18.4, 15.1, 17.4,
       16.3, 17.9, 13.6, 17.4, 15.2, 13.5, 16.6, 15.2, 17.1, 15.4, 17.6,
       16.6, 15.6, 16.4, 15.1, 17.7, 16.2, 17.2, 16.8, 16.9, 17.4, 17.8,
       18.4, 16.9, 14.8, 14.8, 14.6, 15.6, 17.4, 16.4, 17.5, 18. , 16.3,
       16. , 15.3, 15.7, 17.1, 15.6, 13.6, 15.8, 16.1, 16.1, 16.7, 13.7,
       15.9, 21.1, 18.5, 21.1, 19.6, 20.5, 22.3, 16.6, 21.3, 19.8, 22.4,
       19.8, 19.3, 20.4, 18.2, 19.1, 20.2, 19.8, 23.4, 22.5, 17.7, 21.1,
       18.3, 22.2, 18.7, 20.8, 21.2, 18.6, 18.8, 19.9, 20.6, 21.2, 23.1,
       20. , 18.7, 18.7, 22.1, 20.7, 19.8, 18.6, 20.5, 20.8, 20.4, 18.5,
       21.2, 21.2, 20.2, 18.7, 19.7, 20.3, 18.8])

In [80]:
np.min(iris, axis=0)


array([4.3, 2. , 1. , 0.1, 1. ])

In [81]:
np.std(iris, axis=0)

array([0.82530129, 0.43441097, 1.75940407, 0.75969263, 0.81649658])

In [82]:
np.max(iris, axis=0)

array([7.9, 4.4, 6.9, 2.5, 3. ])

In [90]:
iris3 = iris[iris[:,4]== 3]
iris3

array([[6.3, 3.3, 6. , 2.5, 3. ],
       [5.8, 2.7, 5.1, 1.9, 3. ],
       [7.1, 3. , 5.9, 2.1, 3. ],
       [6.3, 2.9, 5.6, 1.8, 3. ],
       [6.5, 3. , 5.8, 2.2, 3. ],
       [7.6, 3. , 6.6, 2.1, 3. ],
       [4.9, 2.5, 4.5, 1.7, 3. ],
       [7.3, 2.9, 6.3, 1.8, 3. ],
       [6.7, 2.5, 5.8, 1.8, 3. ],
       [7.2, 3.6, 6.1, 2.5, 3. ],
       [6.5, 3.2, 5.1, 2. , 3. ],
       [6.4, 2.7, 5.3, 1.9, 3. ],
       [6.8, 3. , 5.5, 2.1, 3. ],
       [5.7, 2.5, 5. , 2. , 3. ],
       [5.8, 2.8, 5.1, 2.4, 3. ],
       [6.4, 3.2, 5.3, 2.3, 3. ],
       [6.5, 3. , 5.5, 1.8, 3. ],
       [7.7, 3.8, 6.7, 2.2, 3. ],
       [7.7, 2.6, 6.9, 2.3, 3. ],
       [6. , 2.2, 5. , 1.5, 3. ],
       [6.9, 3.2, 5.7, 2.3, 3. ],
       [5.6, 2.8, 4.9, 2. , 3. ],
       [7.7, 2.8, 6.7, 2. , 3. ],
       [6.3, 2.7, 4.9, 1.8, 3. ],
       [6.7, 3.3, 5.7, 2.1, 3. ],
       [7.2, 3.2, 6. , 1.8, 3. ],
       [6.2, 2.8, 4.8, 1.8, 3. ],
       [6.1, 3. , 4.9, 1.8, 3. ],
       [6.4, 2.8, 5.6, 2.1, 3. ],
       [7.2, 3

In [88]:
np.mean(iris3, axis=0)

array([6.588, 2.974, 5.552, 2.026, 3.   ])

In [93]:
#np.insert(iris, 3, [[10,10,10,10,10]], axis=0)

In [94]:
iris

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [4.9, 3. , 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.3, 0.2, 1. ],
       [4.6, 3.1, 1.5, 0.2, 1. ],
       [5. , 3.6, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [4.6, 3.4, 1.4, 0.3, 1. ],
       [5. , 3.4, 1.5, 0.2, 1. ],
       [4.4, 2.9, 1.4, 0.2, 1. ],
       [4.9, 3.1, 1.5, 0.1, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [4.8, 3.4, 1.6, 0.2, 1. ],
       [4.8, 3. , 1.4, 0.1, 1. ],
       [4.3, 3. , 1.1, 0.1, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [4.8, 3.4, 1.9, 0.2, 1. ],
       [5. , 3. , 1.6, 0.2, 1. ],
       [5. , 3.4, 1.6, 0.4, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [4.7, 3

In [124]:
moyenne = np.mean(iris, axis=1)

insert_moyenne = np.insert(iris,5,moyenne, axis=1)
insert_moyenne

array([[5.1 , 3.5 , 1.4 , 0.2 , 1.  , 2.24],
       [4.9 , 3.  , 1.4 , 0.2 , 1.  , 2.1 ],
       [4.7 , 3.2 , 1.3 , 0.2 , 1.  , 2.08],
       [4.6 , 3.1 , 1.5 , 0.2 , 1.  , 2.08],
       [5.  , 3.6 , 1.4 , 0.2 , 1.  , 2.24],
       [5.4 , 3.9 , 1.7 , 0.4 , 1.  , 2.48],
       [4.6 , 3.4 , 1.4 , 0.3 , 1.  , 2.14],
       [5.  , 3.4 , 1.5 , 0.2 , 1.  , 2.22],
       [4.4 , 2.9 , 1.4 , 0.2 , 1.  , 1.98],
       [4.9 , 3.1 , 1.5 , 0.1 , 1.  , 2.12],
       [5.4 , 3.7 , 1.5 , 0.2 , 1.  , 2.36],
       [4.8 , 3.4 , 1.6 , 0.2 , 1.  , 2.2 ],
       [4.8 , 3.  , 1.4 , 0.1 , 1.  , 2.06],
       [4.3 , 3.  , 1.1 , 0.1 , 1.  , 1.9 ],
       [5.8 , 4.  , 1.2 , 0.2 , 1.  , 2.44],
       [5.7 , 4.4 , 1.5 , 0.4 , 1.  , 2.6 ],
       [5.4 , 3.9 , 1.3 , 0.4 , 1.  , 2.4 ],
       [5.1 , 3.5 , 1.4 , 0.3 , 1.  , 2.26],
       [5.7 , 3.8 , 1.7 , 0.3 , 1.  , 2.5 ],
       [5.1 , 3.8 , 1.5 , 0.3 , 1.  , 2.34],
       [5.4 , 3.4 , 1.7 , 0.2 , 1.  , 2.34],
       [5.1 , 3.7 , 1.5 , 0.4 , 1.  , 2.34],
       [4.

In [136]:
moyenne_lignes = np.mean(iris, axis=0)

insert_moyenne_lignes = np.insert(iris,iris.shape[0],moyenne_lignes, axis=0)
insert_moyenne_lignes

array([[5.1       , 3.5       , 1.4       , 0.2       , 1.        ],
       [4.9       , 3.        , 1.4       , 0.2       , 1.        ],
       [4.7       , 3.2       , 1.3       , 0.2       , 1.        ],
       [4.6       , 3.1       , 1.5       , 0.2       , 1.        ],
       [5.        , 3.6       , 1.4       , 0.2       , 1.        ],
       [5.4       , 3.9       , 1.7       , 0.4       , 1.        ],
       [4.6       , 3.4       , 1.4       , 0.3       , 1.        ],
       [5.        , 3.4       , 1.5       , 0.2       , 1.        ],
       [4.4       , 2.9       , 1.4       , 0.2       , 1.        ],
       [4.9       , 3.1       , 1.5       , 0.1       , 1.        ],
       [5.4       , 3.7       , 1.5       , 0.2       , 1.        ],
       [4.8       , 3.4       , 1.6       , 0.2       , 1.        ],
       [4.8       , 3.        , 1.4       , 0.1       , 1.        ],
       [4.3       , 3.        , 1.1       , 0.1       , 1.        ],
       [5.8       , 4.        , 1.